ALTER TABLE `app_config`
ADD COLUMN IF NOT EXISTS `ai_invest_url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'AI智投链接',
ADD COLUMN IF NOT EXISTS `insight_url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '洞察链接',
ADD COLUMN IF NOT EXISTS `ai_invest_on` TINYINT NOT NULL DEFAULT 0 COMMENT 'AI智投开关 1:开启 0:关闭',
ADD COLUMN IF NOT EXISTS `insight_connection_on` TINYINT NOT NULL DEFAULT 0 COMMENT '洞察连接开关 1:开启 0:关闭',
ADD COLUMN IF NOT EXISTS `normal_user_can_add_friend` TINYINT NOT NULL DEFAULT 1 COMMENT '普通用户是否可以添加好友 1:可以 0:不可以';